---
# Gather packages
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
  - name: ensure base packages are installed
    apt: pkg={{item}} state=installed
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2
        - python-pip
        - redis-server
        - npm

  - name: alias nodejs
    shell: ln -s /usr/bin/nodejs /usr/bin/node